<?php $this->layout('layout::default', ['title' => 'Contact Us']) ?>

<div class="row">
    <div class="col-md-12">
        <h1>Contact Us</h1>
        <p>
            <strong>Some Company</strong><br /><br />
            
            Phone: 555-555-5555<br /><br />
            
            Address:<br />
            555 Good Street Suite 2<br />
            Any Town, Florida 55555-5555<br />
        </p>
    </div>
</div>